import {
  MOCK_EXAMS,
  MOCK_SUBJECTS,
  MOCK_CHAPTERS,
  MOCK_TESTS,
  MOCK_QUESTIONS,
} from '@/services/mockData';
import type { Database } from '@/types/database';
import type {
  AttemptAnswerState,
  Chapter,
  Exam,
  ExamCategory,
  GradedResult,
  MockTest,
  Question,
  Subject,
  TestAttempt,
  TestSeries,
  CouponItem,
  NotificationItem,
  AppSettingItem,
  SupportTicketItem,
  AdminAuditLog,
  AdminStaffMember,
  QuestionItemAnalysis,
  AdminPaymentRow,
  AdminStudentRow,
  LiveTest,
  LiveTestParticipation,
} from '@/types';

// Shared in-memory fallback stores (used when Supabase is unconfigured).
// Extracted verbatim from the original src/services/api.ts during the domain split.

export type ExamRow = Database['public']['Tables']['exams']['Row'];
export type SubjectRow = Database['public']['Tables']['subjects']['Row'];
export type ChapterRow = Database['public']['Tables']['chapters']['Row'];
export type TestRow = Database['public']['Tables']['tests']['Row'];
export type QuestionRow = Database['public']['Tables']['questions']['Row'];
export type AttemptRow = Database['public']['Tables']['test_attempts']['Row'];
export type MistakeRow = Database['public']['Tables']['mistakes']['Row'];
export type BookmarkRow = Database['public']['Tables']['bookmarks']['Row'];
export type PlanRow = Database['public']['Tables']['subscription_plans']['Row'];

export const localExams: Exam[] = [...MOCK_EXAMS];
export const localSubjects: Subject[] = Object.values(MOCK_SUBJECTS).flat();
export const localChapters: Chapter[] = Object.values(MOCK_CHAPTERS).flat();
export const DEFAULT_SHOWCASE_SERIES: TestSeries[] = [
  {
    id: 'wbp-prelims-2025',
    examId: 'wbp-constable',
    title: 'WBP Constable',
    subtitle: 'Complete Preparation Series',
    slug: 'wbp-constable-complete-series',
    description:
      'WBP Constable পরীক্ষার জন্য সম্পূর্ণ প্রস্তুতি সিরিজ। এখানে রয়েছে ফুল মক টেস্ট, বিষয়ভিত্তিক টেস্ট এবং অফিসিয়াল PYQ, যা আপনার পরীক্ষার প্রস্তুতিকে শক্তিশালী করবে।',
    examTitle: 'WBP Constable',
    examCategory: 'Police',
    isPremium: false,
    orderIndex: 1,
    isActive: true,
    status: 'published',
    iconUrl: '/images/exams/logo_wbp.png',
    fullMockCount: 5,
    topicTestCount: 12,
    pyqTestCount: 8,
    testCount: 25,
    testsCount: 25,
    enrollmentCount: 1240,
    avgCompletion: 78,
    avgAccuracy: 82,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'ssc-mts-2025',
    examId: 'ssc-mts',
    title: 'SSC MTS',
    subtitle: 'Target SSC MTS 2025',
    slug: 'ssc-mts-target-2025',
    description:
      'Staff Selection Commission MTS complete mock drill and chapter-wise tests in Bengali & English.',
    examTitle: 'SSC MTS',
    examCategory: 'SSC & Central Govt.',
    isPremium: false,
    orderIndex: 2,
    isActive: true,
    status: 'published',
    iconUrl: '/images/exams/logo_ssc.png',
    fullMockCount: 6,
    topicTestCount: 15,
    pyqTestCount: 10,
    testCount: 31,
    testsCount: 31,
    enrollmentCount: 860,
    avgCompletion: 74,
    avgAccuracy: 79,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'railway-group-d-2025',
    examId: 'railway-group-d',
    title: 'Railway Group D',
    subtitle: 'Complete Test Series',
    slug: 'railway-group-d-complete',
    description:
      'RRB Group D CBT full mocks, science specials, reasoning drills, and previous years official papers.',
    examTitle: 'Railway Group D',
    examCategory: 'Railways (RRB)',
    isPremium: false,
    orderIndex: 3,
    isActive: true,
    status: 'published',
    iconUrl: '/images/exams/logo_railway.png',
    fullMockCount: 8,
    topicTestCount: 20,
    pyqTestCount: 12,
    testCount: 40,
    testsCount: 40,
    enrollmentCount: 620,
    avgCompletion: 71,
    avgAccuracy: 76,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'wbpsc-clerkship-2025',
    examId: 'wbpsc-clerkship',
    title: 'WBPSC Clerkship',
    subtitle: 'Mock Test Series 2025',
    slug: 'wbpsc-clerkship-mock-2025',
    description:
      'WBPSC Clerkship Part 1 General Studies, Arithmetic, and English dedicated mock test series.',
    examTitle: 'WBPSC Clerkship',
    examCategory: 'WBPSC',
    isPremium: false,
    orderIndex: 4,
    isActive: true,
    status: 'published',
    iconUrl: '/images/exams/logo_wbpsc.png',
    fullMockCount: 5,
    topicTestCount: 18,
    pyqTestCount: 10,
    testCount: 33,
    testsCount: 33,
    enrollmentCount: 410,
    avgCompletion: 76,
    avgAccuracy: 81,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'icds-supervisor-2025',
    examId: 'icds-supervisor',
    title: 'ICDS Supervisor',
    subtitle: 'Practice & PYQ Series',
    slug: 'icds-supervisor-practice',
    description:
      'Integrated Child Development Services Supervisor preliminary and mains mock tests.',
    examTitle: 'ICDS',
    examCategory: 'WBPSC',
    isPremium: false,
    orderIndex: 5,
    isActive: false,
    status: 'draft',
    iconUrl: '/images/exams/logo_wbtet.png',
    fullMockCount: 4,
    topicTestCount: 14,
    pyqTestCount: 8,
    testCount: 26,
    testsCount: 26,
    enrollmentCount: 320,
    avgCompletion: 65,
    avgAccuracy: 72,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'food-si-2025',
    examId: 'food-si',
    title: 'Food SI',
    subtitle: 'Full Preparation Series',
    slug: 'food-si-full-prep',
    description:
      'WBPSC Sub-Inspector in Food & Supplies department 100-mark full mock drills.',
    examTitle: 'Food SI',
    examCategory: 'WBPSC',
    isPremium: false,
    orderIndex: 6,
    isActive: true,
    status: 'published',
    iconUrl: '/images/exams/logo_wbp.png',
    fullMockCount: 6,
    topicTestCount: 16,
    pyqTestCount: 9,
    testCount: 31,
    testsCount: 31,
    enrollmentCount: 290,
    avgCompletion: 80,
    avgAccuracy: 83,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'wbpsc-misc-2025',
    examId: 'wbpsc-misc',
    title: 'WBPSC Miscellaneous',
    subtitle: 'Topic + Mock + PYQ',
    slug: 'wbpsc-misc-topic-mock',
    description:
      'WBPSC Miscellaneous Services Prelims and Mains oriented chapter drills.',
    examTitle: 'WBPSC Misc',
    examCategory: 'WBPSC',
    isPremium: false,
    orderIndex: 7,
    isActive: true,
    status: 'published',
    iconUrl: '/images/exams/logo_wbpsc.png',
    fullMockCount: 5,
    topicTestCount: 12,
    pyqTestCount: 7,
    testCount: 24,
    testsCount: 24,
    enrollmentCount: 260,
    avgCompletion: 69,
    avgAccuracy: 75,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'kolkata-police-2025',
    examId: 'kolkata-police',
    title: 'Kolkata Police',
    subtitle: 'Practice Series',
    slug: 'kolkata-police-practice',
    description:
      'KP Constable & Lady Constable full mock tests and speed calculations.',
    examTitle: 'Kolkata Police',
    examCategory: 'Police',
    isPremium: false,
    orderIndex: 8,
    isActive: false,
    status: 'under_review',
    iconUrl: '/images/exams/icon_kolkata_police.png',
    fullMockCount: 4,
    topicTestCount: 10,
    pyqTestCount: 6,
    testCount: 20,
    testsCount: 20,
    enrollmentCount: 210,
    avgCompletion: 72,
    avgAccuracy: 77,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'ssc-gd-2025',
    examId: 'ssc-gd',
    title: 'SSC GD',
    subtitle: 'Complete Test Series',
    slug: 'ssc-gd-complete-series',
    description:
      'SSC GD Constable General Intelligence, Math, Elementary English & Hindi, and GK drills.',
    examTitle: 'SSC GD',
    examCategory: 'SSC & Central Govt.',
    isPremium: false,
    orderIndex: 9,
    isActive: true,
    status: 'published',
    iconUrl: '/images/exams/logo_ssc.png',
    fullMockCount: 6,
    topicTestCount: 14,
    pyqTestCount: 10,
    testCount: 30,
    testsCount: 30,
    enrollmentCount: 190,
    avgCompletion: 75,
    avgAccuracy: 80,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gk-practice-2025',
    examId: 'general-knowledge',
    title: 'General Knowledge',
    subtitle: 'GK Practice Series',
    slug: 'gk-practice-series',
    description:
      'Comprehensive static GK, Indian History, Geography, Polity, Science topic-wise test packs.',
    examTitle: 'General Knowledge',
    examCategory: 'General Knowledge',
    isPremium: false,
    orderIndex: 10,
    isActive: true,
    status: 'published',
    iconUrl: '/images/exams/logo_railway.png',
    fullMockCount: 3,
    topicTestCount: 20,
    pyqTestCount: 5,
    testCount: 28,
    testsCount: 28,
    enrollmentCount: 160,
    avgCompletion: 82,
    avgAccuracy: 85,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'wbtet-primary-2025',
    examId: 'wbtet-primary',
    title: 'WBTET Primary',
    subtitle: 'Primary TET Mock Pack',
    slug: 'wbtet-primary-mock-pack',
    description:
      'West Bengal Primary Teacher Eligibility Test Child Development & Pedagogy, Bengali, EVS, and Math.',
    examTitle: 'WBTET Primary',
    examCategory: 'Teaching',
    isPremium: false,
    orderIndex: 11,
    isActive: false,
    status: 'draft',
    iconUrl: '/images/exams/logo_wbtet.png',
    fullMockCount: 4,
    topicTestCount: 12,
    pyqTestCount: 6,
    testCount: 22,
    testsCount: 22,
    enrollmentCount: 130,
    avgCompletion: 60,
    avgAccuracy: 68,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'wbcs-prelims-2025',
    examId: 'wbcs-prelims',
    title: 'WBCS Executive',
    subtitle: 'Prelims Mock Series',
    slug: 'wbcs-prelims-series',
    description:
      'West Bengal Civil Services Preliminary Examination 200-question comprehensive full mocks.',
    examTitle: 'WBCS Prelims',
    examCategory: 'WBPSC',
    isPremium: true,
    orderIndex: 12,
    isActive: true,
    status: 'published',
    iconUrl: '/images/exams/logo_wbpsc.png',
    fullMockCount: 8,
    topicTestCount: 25,
    pyqTestCount: 15,
    testCount: 48,
    testsCount: 48,
    enrollmentCount: 980,
    avgCompletion: 73,
    avgAccuracy: 78,
    createdAt: '2026-01-01T00:00:00Z',
  },
];

export const localTestSeries: TestSeries[] = [...DEFAULT_SHOWCASE_SERIES];
export const localTests: MockTest[] = Object.values(MOCK_TESTS).flat();
export const localQuestions: Question[] = Object.values(MOCK_QUESTIONS).flat();

export const localLiveTests: LiveTest[] = [
  {
    id: 'live-test-001',
    testId: 'test-wbp-mock-01',
    title: 'WBP Constable Live Test 01',
    testTitle: 'Full Mock Test',
    examTitle: 'WBP Constable',
    examId: 'wbp-constable',
    status: 'live',
    startAt: '2026-09-30T10:00:00.000Z',
    registrationDeadline: '2026-09-30T09:55:00.000Z',
    scheduledStartTime: '2026-09-30T10:00:00.000Z',
    scheduledEndTime: '2026-09-30T11:00:00.000Z',
    scheduledStartAt: '2026-09-30T10:00:00.000Z',
    scheduledEndAt: '2026-09-30T11:00:00.000Z',
    durationMinutes: 60,
    totalQuestions: 100,
    totalMarks: 100,
    negativeMarking: 0.25,
    participantsCount: 1248,
    enrolledCount: 1835,
    logo: '/images/exams/logo_wbp.png',
    examLogo: '/images/exams/logo_wbp.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: true,
    instructions: 'Official West Bengal Police Constable pattern. 100 Questions, 60 Minutes, 0.25 Negative Marking. Statewide ranking and detailed analysis will be available immediately upon completion.',
    createdAt: '2026-09-25T16:20:00.000Z',
    updatedAt: '2026-09-30T08:15:00.000Z',
  },
  {
    id: 'live-test-002',
    testId: 'test-ssc-mts-01',
    title: 'SSC MTS Live Test 01',
    testTitle: 'Full Mock Test',
    examTitle: 'SSC MTS',
    examId: 'ssc-mts',
    status: 'upcoming',
    startAt: '2026-10-02T14:00:00.000Z',
    registrationDeadline: '2026-10-02T13:55:00.000Z',
    scheduledStartTime: '2026-10-02T14:00:00.000Z',
    scheduledEndTime: '2026-10-02T15:00:00.000Z',
    scheduledStartAt: '2026-10-02T14:00:00.000Z',
    scheduledEndAt: '2026-10-02T15:00:00.000Z',
    durationMinutes: 60,
    totalQuestions: 90,
    totalMarks: 90,
    negativeMarking: 0.25,
    participantsCount: 642,
    enrolledCount: 950,
    logo: '/images/exams/logo_ssc.png',
    examLogo: '/images/exams/logo_ssc.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: true,
    instructions: 'Staff Selection Commission Multi-Tasking Staff full live test.',
    createdAt: '2026-09-26T11:00:00.000Z',
    updatedAt: '2026-09-26T11:00:00.000Z',
  },
  {
    id: 'live-test-003',
    testId: 'test-wbcs-pre-01',
    title: 'WBCS Prelims Live Test 01',
    testTitle: 'Full Mock Test',
    examTitle: 'WBCS',
    examId: 'wbcs',
    status: 'upcoming',
    startAt: '2026-10-05T10:00:00.000Z',
    registrationDeadline: '2026-10-05T09:55:00.000Z',
    scheduledStartTime: '2026-10-05T10:00:00.000Z',
    scheduledEndTime: '2026-10-05T12:00:00.000Z',
    scheduledStartAt: '2026-10-05T10:00:00.000Z',
    scheduledEndAt: '2026-10-05T12:00:00.000Z',
    durationMinutes: 120,
    totalQuestions: 200,
    totalMarks: 200,
    negativeMarking: 0.33,
    participantsCount: 1020,
    enrolledCount: 1400,
    logo: '/images/exams/logo_wbpsc.png',
    examLogo: '/images/exams/logo_wbpsc.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: true,
    instructions: 'West Bengal Civil Service preliminary full syllabus mock test.',
    createdAt: '2026-09-27T09:00:00.000Z',
    updatedAt: '2026-09-27T09:00:00.000Z',
  },
  {
    id: 'live-test-004',
    testId: 'test-railway-ntpc-01',
    title: 'Railway NTPC Live Test 01',
    testTitle: 'Full Mock Test',
    examTitle: 'Railway (NTPC)',
    examId: 'railway-ntpc',
    status: 'draft',
    startAt: '2026-10-08T16:00:00.000Z',
    registrationDeadline: '2026-10-08T15:55:00.000Z',
    scheduledStartTime: '2026-10-08T16:00:00.000Z',
    scheduledEndTime: '2026-10-08T17:30:00.000Z',
    scheduledStartAt: '2026-10-08T16:00:00.000Z',
    scheduledEndAt: '2026-10-08T17:30:00.000Z',
    durationMinutes: 90,
    totalQuestions: 100,
    totalMarks: 100,
    negativeMarking: 0.33,
    participantsCount: 780,
    enrolledCount: 1100,
    logo: '/images/exams/logo_railway.png',
    examLogo: '/images/exams/logo_railway.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: false,
    instructions: 'Railway NTPC CBT-1 exam live test.',
    createdAt: '2026-09-28T14:00:00.000Z',
    updatedAt: '2026-09-28T14:00:00.000Z',
  },
  {
    id: 'live-test-005',
    testId: 'test-wbpsc-clerk-01',
    title: 'WBPSC Clerkship Live Test 01',
    testTitle: 'Full Mock Test',
    examTitle: 'WBPSC Clerkship',
    examId: 'wbpsc-clerkship',
    status: 'upcoming',
    startAt: '2026-10-12T10:00:00.000Z',
    registrationDeadline: '2026-10-12T09:55:00.000Z',
    scheduledStartTime: '2026-10-12T10:00:00.000Z',
    scheduledEndTime: '2026-10-12T11:30:00.000Z',
    scheduledStartAt: '2026-10-12T10:00:00.000Z',
    scheduledEndAt: '2026-10-12T11:30:00.000Z',
    durationMinutes: 90,
    totalQuestions: 100,
    totalMarks: 100,
    negativeMarking: 0.25,
    participantsCount: 924,
    enrolledCount: 1250,
    logo: '/images/exams/logo_wbpsc.png',
    examLogo: '/images/exams/logo_wbpsc.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: true,
    instructions: 'WBPSC Clerkship Part-I examination format live test.',
    createdAt: '2026-09-29T10:00:00.000Z',
    updatedAt: '2026-09-29T10:00:00.000Z',
  },
  {
    id: 'live-test-006',
    testId: 'test-food-si-01',
    title: 'Food SI Live Test 01',
    testTitle: 'Full Mock Test',
    examTitle: 'Food SI',
    examId: 'wb-food-si',
    status: 'upcoming',
    startAt: '2026-10-15T14:00:00.000Z',
    registrationDeadline: '2026-10-15T13:55:00.000Z',
    scheduledStartTime: '2026-10-15T14:00:00.000Z',
    scheduledEndTime: '2026-10-15T15:00:00.000Z',
    scheduledStartAt: '2026-10-15T14:00:00.000Z',
    scheduledEndAt: '2026-10-15T15:00:00.000Z',
    durationMinutes: 60,
    totalQuestions: 100,
    totalMarks: 100,
    negativeMarking: 0.25,
    participantsCount: 568,
    enrolledCount: 890,
    logo: '/images/exams/logo_wbpsc.png',
    examLogo: '/images/exams/logo_wbpsc.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: true,
    instructions: 'WBPSC Food Sub-Inspector recruitment live mock examination.',
    createdAt: '2026-09-29T15:00:00.000Z',
    updatedAt: '2026-09-29T15:00:00.000Z',
  },
  {
    id: 'live-test-007',
    testId: 'test-kp-si-01',
    title: 'KP SI Live Test 01',
    testTitle: 'Full Mock Test',
    examTitle: 'KP SI',
    examId: 'kp-si',
    status: 'draft',
    startAt: '2026-10-20T10:00:00.000Z',
    registrationDeadline: '2026-10-20T09:55:00.000Z',
    scheduledStartTime: '2026-10-20T10:00:00.000Z',
    scheduledEndTime: '2026-10-20T11:30:00.000Z',
    scheduledStartAt: '2026-10-20T10:00:00.000Z',
    scheduledEndAt: '2026-10-20T11:30:00.000Z',
    durationMinutes: 90,
    totalQuestions: 100,
    totalMarks: 100,
    negativeMarking: 0.25,
    participantsCount: 0,
    enrolledCount: 0,
    logo: '/images/exams/logo_wbp.png',
    examLogo: '/images/exams/logo_wbp.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: false,
    instructions: 'Kolkata Police Sub-Inspector preliminary live test draft.',
    createdAt: '2026-09-30T09:00:00.000Z',
    updatedAt: '2026-09-30T09:00:00.000Z',
  },
  {
    id: 'live-test-008',
    testId: 'test-wbp-02',
    title: 'WBP Constable Live Test 02',
    testTitle: 'Full Mock Test',
    examTitle: 'WBP Constable',
    examId: 'wbp-constable',
    status: 'upcoming',
    startAt: '2026-10-25T10:00:00.000Z',
    registrationDeadline: '2026-10-25T09:55:00.000Z',
    scheduledStartTime: '2026-10-25T10:00:00.000Z',
    scheduledEndTime: '2026-10-25T11:00:00.000Z',
    scheduledStartAt: '2026-10-25T10:00:00.000Z',
    scheduledEndAt: '2026-10-25T11:00:00.000Z',
    durationMinutes: 60,
    totalQuestions: 100,
    totalMarks: 100,
    negativeMarking: 0.25,
    participantsCount: 0,
    enrolledCount: 0,
    logo: '/images/exams/logo_wbp.png',
    examLogo: '/images/exams/logo_wbp.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: true,
    instructions: 'West Bengal Police Constable Live Mock Test 02.',
    createdAt: '2026-09-30T10:00:00.000Z',
    updatedAt: '2026-09-30T10:00:00.000Z',
  },
  {
    id: 'live-test-009',
    testId: 'test-ssc-gd-01',
    title: 'SSC GD Live Test 01',
    testTitle: 'Full Mock Test',
    examTitle: 'SSC GD',
    examId: 'ssc-gd',
    status: 'upcoming',
    startAt: '2026-10-28T14:00:00.000Z',
    registrationDeadline: '2026-10-28T13:55:00.000Z',
    scheduledStartTime: '2026-10-28T14:00:00.000Z',
    scheduledEndTime: '2026-10-28T15:00:00.000Z',
    scheduledStartAt: '2026-10-28T14:00:00.000Z',
    scheduledEndAt: '2026-10-28T15:00:00.000Z',
    durationMinutes: 60,
    totalQuestions: 80,
    totalMarks: 160,
    negativeMarking: 0.5,
    participantsCount: 0,
    enrolledCount: 0,
    logo: '/images/exams/logo_ssc.png',
    examLogo: '/images/exams/logo_ssc.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: true,
    instructions: 'SSC GD Constable live mock test examination.',
    createdAt: '2026-09-30T11:00:00.000Z',
    updatedAt: '2026-09-30T11:00:00.000Z',
  },
  {
    id: 'live-test-010',
    testId: 'test-wbcs-mains-01',
    title: 'WBCS Mains Live Test 01',
    testTitle: 'Full Mock Test',
    examTitle: 'WBCS',
    examId: 'wbcs',
    status: 'draft',
    startAt: '2026-11-01T10:00:00.000Z',
    registrationDeadline: '2026-11-01T09:55:00.000Z',
    scheduledStartTime: '2026-11-01T10:00:00.000Z',
    scheduledEndTime: '2026-11-01T13:00:00.000Z',
    scheduledStartAt: '2026-11-01T10:00:00.000Z',
    scheduledEndAt: '2026-11-01T13:00:00.000Z',
    durationMinutes: 180,
    totalQuestions: 200,
    totalMarks: 200,
    negativeMarking: 0.33,
    participantsCount: 0,
    enrolledCount: 0,
    logo: '/images/exams/logo_wbpsc.png',
    examLogo: '/images/exams/logo_wbpsc.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: false,
    instructions: 'WBCS Mains full mock live test draft.',
    createdAt: '2026-09-30T12:00:00.000Z',
    updatedAt: '2026-09-30T12:00:00.000Z',
  },
  // 11 to 23: 13 Completed live tests (to total exactly 18 completed, 23 total, 24,860 participants)
  {
    id: 'live-test-011',
    testId: 'test-wbp-si-comp',
    title: 'WBP SI Preliminary Live 01',
    testTitle: 'Full Mock Test',
    examTitle: 'WBP Constable',
    examId: 'wbp-constable',
    status: 'ended',
    startAt: '2026-09-24T10:00:00.000Z',
    scheduledStartTime: '2026-09-24T10:00:00.000Z',
    durationMinutes: 90,
    totalQuestions: 100,
    totalMarks: 100,
    negativeMarking: 0.25,
    participantsCount: 1420,
    enrolledCount: 1650,
    logo: '/images/exams/logo_wbp.png',
    examLogo: '/images/exams/logo_wbp.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: true,
    createdAt: '2026-09-20T10:00:00.000Z',
  },
  {
    id: 'live-test-012',
    testId: 'test-wbpsc-misc-comp',
    title: 'WBPSC Miscellaneous Live Test',
    testTitle: 'Full Mock Test',
    examTitle: 'WBPSC Clerkship',
    examId: 'wbpsc-clerkship',
    status: 'ended',
    startAt: '2026-09-22T10:00:00.000Z',
    scheduledStartTime: '2026-09-22T10:00:00.000Z',
    durationMinutes: 90,
    totalQuestions: 100,
    totalMarks: 100,
    negativeMarking: 0.25,
    participantsCount: 1280,
    enrolledCount: 1500,
    logo: '/images/exams/logo_wbpsc.png',
    examLogo: '/images/exams/logo_wbpsc.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: true,
    createdAt: '2026-09-18T10:00:00.000Z',
  },
  {
    id: 'live-test-013',
    testId: 'test-kp-const-comp',
    title: 'Kolkata Police Constable Live Test 01',
    testTitle: 'Full Mock Test',
    examTitle: 'KP SI',
    examId: 'kp-si',
    status: 'ended',
    startAt: '2026-09-20T10:00:00.000Z',
    scheduledStartTime: '2026-09-20T10:00:00.000Z',
    durationMinutes: 60,
    totalQuestions: 100,
    totalMarks: 100,
    negativeMarking: 0.25,
    participantsCount: 2150,
    enrolledCount: 2500,
    logo: '/images/exams/logo_wbp.png',
    examLogo: '/images/exams/logo_wbp.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: true,
    createdAt: '2026-09-15T10:00:00.000Z',
  },
  {
    id: 'live-test-014',
    testId: 'test-rrb-grp-comp',
    title: 'Railway Group D Science & Math Live 01',
    testTitle: 'Full Mock Test',
    examTitle: 'Railway (NTPC)',
    examId: 'railway-ntpc',
    status: 'ended',
    startAt: '2026-09-18T16:00:00.000Z',
    scheduledStartTime: '2026-09-18T16:00:00.000Z',
    durationMinutes: 90,
    totalQuestions: 100,
    totalMarks: 100,
    negativeMarking: 0.33,
    participantsCount: 1640,
    enrolledCount: 1950,
    logo: '/images/exams/logo_railway.png',
    examLogo: '/images/exams/logo_railway.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: true,
    createdAt: '2026-09-14T10:00:00.000Z',
  },
  {
    id: 'live-test-015',
    testId: 'test-tet-mock-comp',
    title: 'Primary TET Special Mock Live 01',
    testTitle: 'Full Mock Test',
    examTitle: 'Primary TET',
    examId: 'primary-tet',
    status: 'ended',
    startAt: '2026-09-16T10:00:00.000Z',
    scheduledStartTime: '2026-09-16T10:00:00.000Z',
    durationMinutes: 150,
    totalQuestions: 150,
    totalMarks: 150,
    negativeMarking: 0,
    participantsCount: 1890,
    enrolledCount: 2200,
    logo: '/images/exams/logo_wbtet.png',
    examLogo: '/images/exams/logo_wbtet.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: true,
    createdAt: '2026-09-12T10:00:00.000Z',
  },
  {
    id: 'live-test-016',
    testId: 'test-ssc-cgl-comp',
    title: 'SSC CGL Tier-I Mega Live Test 01',
    testTitle: 'Full Mock Test',
    examTitle: 'SSC MTS',
    examId: 'ssc-mts',
    status: 'ended',
    startAt: '2026-09-14T14:00:00.000Z',
    scheduledStartTime: '2026-09-14T14:00:00.000Z',
    durationMinutes: 60,
    totalQuestions: 100,
    totalMarks: 200,
    negativeMarking: 0.5,
    participantsCount: 2420,
    enrolledCount: 2900,
    logo: '/images/exams/logo_ssc.png',
    examLogo: '/images/exams/logo_ssc.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: true,
    createdAt: '2026-09-10T10:00:00.000Z',
  },
  {
    id: 'live-test-017',
    testId: 'test-wb-audit-comp',
    title: 'WB Audit & Accounts Preliminary Live',
    testTitle: 'Full Mock Test',
    examTitle: 'WBCS',
    examId: 'wbcs',
    status: 'ended',
    startAt: '2026-09-12T10:00:00.000Z',
    scheduledStartTime: '2026-09-12T10:00:00.000Z',
    durationMinutes: 120,
    totalQuestions: 200,
    totalMarks: 200,
    negativeMarking: 0.33,
    participantsCount: 840,
    enrolledCount: 1050,
    logo: '/images/exams/logo_wbpsc.png',
    examLogo: '/images/exams/logo_wbpsc.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: true,
    createdAt: '2026-09-08T10:00:00.000Z',
  },
  {
    id: 'live-test-018',
    testId: 'test-icds-comp',
    title: 'ICDS Supervisor Special Mock Live',
    testTitle: 'Full Mock Test',
    examTitle: 'Food SI',
    examId: 'wb-food-si',
    status: 'ended',
    startAt: '2026-09-10T10:00:00.000Z',
    scheduledStartTime: '2026-09-10T10:00:00.000Z',
    durationMinutes: 90,
    totalQuestions: 100,
    totalMarks: 100,
    negativeMarking: 0.25,
    participantsCount: 1120,
    enrolledCount: 1350,
    logo: '/images/exams/logo_wbpsc.png',
    examLogo: '/images/exams/logo_wbpsc.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: true,
    createdAt: '2026-09-06T10:00:00.000Z',
  },
  {
    id: 'live-test-019',
    testId: 'test-wbp-weekly-comp',
    title: 'WBP Constable Weekly Live Test 01',
    testTitle: 'Full Mock Test',
    examTitle: 'WBP Constable',
    examId: 'wbp-constable',
    status: 'ended',
    startAt: '2026-09-08T10:00:00.000Z',
    scheduledStartTime: '2026-09-08T10:00:00.000Z',
    durationMinutes: 60,
    totalQuestions: 100,
    totalMarks: 100,
    negativeMarking: 0.25,
    participantsCount: 1930,
    enrolledCount: 2200,
    logo: '/images/exams/logo_wbp.png',
    examLogo: '/images/exams/logo_wbp.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: true,
    createdAt: '2026-09-04T10:00:00.000Z',
  },
  {
    id: 'live-test-020',
    testId: 'test-wbpsc-gs-comp',
    title: 'WBPSC Clerkship General Studies Live',
    testTitle: 'Full Mock Test',
    examTitle: 'WBPSC Clerkship',
    examId: 'wbpsc-clerkship',
    status: 'ended',
    startAt: '2026-09-06T10:00:00.000Z',
    scheduledStartTime: '2026-09-06T10:00:00.000Z',
    durationMinutes: 90,
    totalQuestions: 100,
    totalMarks: 100,
    negativeMarking: 0.25,
    participantsCount: 1210,
    enrolledCount: 1450,
    logo: '/images/exams/logo_wbpsc.png',
    examLogo: '/images/exams/logo_wbpsc.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: true,
    createdAt: '2026-09-02T10:00:00.000Z',
  },
  {
    id: 'live-test-021',
    testId: 'test-rrb-ntpc-cbt1-comp',
    title: 'Railway NTPC CBT-1 Mock Live 02',
    testTitle: 'Full Mock Test',
    examTitle: 'Railway (NTPC)',
    examId: 'railway-ntpc',
    status: 'ended',
    startAt: '2026-09-04T16:00:00.000Z',
    scheduledStartTime: '2026-09-04T16:00:00.000Z',
    durationMinutes: 90,
    totalQuestions: 100,
    totalMarks: 100,
    negativeMarking: 0.33,
    participantsCount: 1510,
    enrolledCount: 1800,
    logo: '/images/exams/logo_railway.png',
    examLogo: '/images/exams/logo_railway.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: true,
    createdAt: '2026-08-30T10:00:00.000Z',
  },
  {
    id: 'live-test-022',
    testId: 'test-kp-si-comp-2',
    title: 'Kolkata Police SI Preliminary Live',
    testTitle: 'Full Mock Test',
    examTitle: 'KP SI',
    examId: 'kp-si',
    status: 'ended',
    startAt: '2026-09-02T10:00:00.000Z',
    scheduledStartTime: '2026-09-02T10:00:00.000Z',
    durationMinutes: 90,
    totalQuestions: 100,
    totalMarks: 100,
    negativeMarking: 0.25,
    participantsCount: 1020,
    enrolledCount: 1250,
    logo: '/images/exams/logo_wbp.png',
    examLogo: '/images/exams/logo_wbp.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: true,
    createdAt: '2026-08-28T10:00:00.000Z',
  },
  {
    id: 'live-test-023',
    testId: 'test-ssc-chsl-comp',
    title: 'SSC CHSL Tier-I All Bengal Live 01',
    testTitle: 'Full Mock Test',
    examTitle: 'SSC GD',
    examId: 'ssc-gd',
    status: 'ended',
    startAt: '2026-09-01T14:00:00.000Z',
    scheduledStartTime: '2026-09-01T14:00:00.000Z',
    durationMinutes: 60,
    totalQuestions: 100,
    totalMarks: 200,
    negativeMarking: 0.5,
    participantsCount: 1248,
    enrolledCount: 1600,
    logo: '/images/exams/logo_ssc.png',
    examLogo: '/images/exams/logo_ssc.png',
    rankingEnabled: true,
    subscriptionRequired: false,
    isPublished: true,
    createdAt: '2026-08-25T10:00:00.000Z',
  },
];


export const localLiveTestParticipations: LiveTestParticipation[] = [
  {
    id: 'part-demo-1',
    liveTestId: 'live-wbp-weekly-01',
    userId: 'mock-user-1',
    registeredAt: new Date(Date.now() - 3600000).toISOString(),
    joinedAt: new Date(Date.now() - 3500000).toISOString(),
    completedAt: new Date(Date.now() - 1000000).toISOString(),
    status: 'completed',
    score: 82.5,
    accuracy: 91.2,
    timeTaken: 3840,
    rank: 1,
    fullName: 'Sourav Ganguly',
    district: 'Kolkata',
  },
  {
    id: 'part-demo-2',
    liveTestId: 'live-wbp-weekly-01',
    userId: 'mock-user-2',
    registeredAt: new Date(Date.now() - 3600000).toISOString(),
    joinedAt: new Date(Date.now() - 3500000).toISOString(),
    completedAt: new Date(Date.now() - 1100000).toISOString(),
    status: 'completed',
    score: 79.0,
    accuracy: 88.0,
    timeTaken: 4120,
    rank: 2,
    fullName: 'Ananya Roy',
    district: 'North 24 Parganas',
  },
  {
    id: 'part-demo-3',
    liveTestId: 'live-wbp-weekly-01',
    userId: 'mock-user-3',
    registeredAt: new Date(Date.now() - 3600000).toISOString(),
    joinedAt: new Date(Date.now() - 3500000).toISOString(),
    completedAt: new Date(Date.now() - 1200000).toISOString(),
    status: 'completed',
    score: 74.5,
    accuracy: 84.5,
    timeTaken: 4500,
    rank: 3,
    fullName: 'Rahul Karmakar',
    district: 'Hooghly',
  },
];

export const localExamCategories: ExamCategory[] = [
  { id: 'cat_wb_police', name: 'WB Police (WBP / KP)', orderIndex: 1, isActive: true },
  { id: 'cat_wbpsc', name: 'WBPSC (Clerkship / WBCS)', orderIndex: 2, isActive: true },
  { id: 'cat_teaching', name: 'Teaching (TET / SLST)', orderIndex: 3, isActive: true },
  { id: 'cat_ssc', name: 'SSC & Central Govt.', orderIndex: 4, isActive: true },
  { id: 'cat_railways', name: 'Railways (RRB)', orderIndex: 5, isActive: true },
];

// Local test-question assignments store for offline demo
export const localTestQuestions: {
  id: string;
  testId: string;
  questionId: string;
  questionOrder: number;
  marks: number;
  negativeMarks: number;
}[] = [];

// Initialize localTestQuestions from MOCK_QUESTIONS and MOCK_TESTS
Object.entries(MOCK_QUESTIONS).forEach(([testId, questions]) => {
  questions.forEach((q, idx) => {
    localTestQuestions.push({
      id: `tq-${testId}-${q.id}`,
      testId,
      questionId: q.id,
      questionOrder: idx + 1,
      marks: q.defaultMarks || 1.0,
      // Questions never carry negative marks — scoring uses the test-level scheme.
      negativeMarks: q.defaultNegativeMarks || 0,
    });
  });
});

// Local in-memory store for session attempts & submissions (for fallback/offline demo)
export const localAttemptsStore: Record<
  string,
  {
    attempt: TestAttempt;
    answers: Record<string, AttemptAnswerState>;
    result?: GradedResult;
  }
> = {};

// Local in-memory store for promotional coupons
export const localCoupons: CouponItem[] = [
  {
    id: 'coupon_welcome50',
    code: 'WELCOME50',
    description: 'Special ₹50 introductory discount for new aspirants',
    discountType: 'fixed',
    discountValue: 50,
    minOrderAmount: 199,
    maxUses: 500,
    usedCount: 38,
    maxUsesPerUser: 1,
    applicablePlanId: 'pro_1_year',
    validFrom: new Date(Date.now() - 30 * 86400000).toISOString(),
    validUntil: new Date(Date.now() + 150 * 86400000).toISOString(),
    isActive: true,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'coupon_festive20',
    code: 'FESTIVE20',
    description: 'Festive 20% discount on 1-Year All-Access Pro Pass',
    discountType: 'percentage',
    discountValue: 20,
    maxDiscountAmount: 100,
    minOrderAmount: 299,
    maxUses: 1000,
    usedCount: 142,
    maxUsesPerUser: 1,
    applicablePlanId: 'pro_1_year',
    validFrom: new Date(Date.now() - 15 * 86400000).toISOString(),
    validUntil: new Date(Date.now() + 75 * 86400000).toISOString(),
    isActive: true,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'coupon_propass100',
    code: 'PROPASS100',
    description: 'Special seasonal ₹100 flat off on Pro Pass',
    discountType: 'fixed',
    discountValue: 100,
    minOrderAmount: 299,
    maxUses: 250,
    usedCount: 89,
    maxUsesPerUser: 1,
    applicablePlanId: 'pro_1_year',
    validFrom: new Date(Date.now() - 5 * 86400000).toISOString(),
    validUntil: new Date(Date.now() + 55 * 86400000).toISOString(),
    isActive: true,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];

// Fallback in-memory notification store
export const localNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'New WBP Constable Full Mock Test 05 Released',
    message:
      'The latest Full Mock Test is now live for all enrolled students. Complete your full 85-question simulation.',
    targetAudience: 'all',
    channel: 'in_app',
    status: 'sent',
    sentAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'notif-pro-1',
    title: 'Pro Exclusive: New Subject-Wise GK Marathon Released',
    message:
      'Special 1500+ curated GK & Static Awareness question drill is now available for all Pro Pass aspirants.',
    targetAudience: 'pro',
    channel: 'in_app',
    status: 'sent',
    sentAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
  {
    id: 'notif-free-1',
    title: 'Free Mock Test Available Today',
    message:
      'Take our free weekly demo mock test to analyze your West Bengal Police preparation level!',
    targetAudience: 'free',
    channel: 'in_app',
    status: 'sent',
    sentAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
  },
];

export function syncLocalScheduledNotifications(): NotificationItem[] {
  const now = new Date();
  localNotifications.forEach((n) => {
    if (n.status === 'scheduled' && n.scheduledAt && new Date(n.scheduledAt) <= now) {
      n.status = 'sent';
      n.sentAt = n.scheduledAt;
    }
  });
  return localNotifications;
}

export const localAppSettings: AppSettingItem[] = [
  {
    id: 'general_app_name',
    category: 'general',
    key: 'app_name',
    value: 'PracticeKoro',
    description: 'Platform name displayed across UI',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'general_support_email',
    category: 'general',
    key: 'support_email',
    value: 'support@practicekoro.online',
    description: 'Support contact email',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'general_support_phone',
    category: 'general',
    key: 'support_phone',
    value: '+91 9547771118',
    description: 'Support phone helpline',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'general_support_whatsapp',
    category: 'general',
    key: 'support_whatsapp',
    value: '+91 9547771118',
    description: 'Official WhatsApp customer support helpline',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'general_support_hours',
    category: 'general',
    key: 'support_hours',
    value: 'Mon - Sat: 10:00 AM - 7:00 PM (IST)',
    description: 'Customer support desk operational hours',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'general_support_address',
    category: 'general',
    key: 'support_address',
    value: 'West Bengal, India',
    description: 'Registered operating location & jurisdiction',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'general_website_url',
    category: 'general',
    key: 'website_url',
    value: 'https://practicekoro.online',
    description: 'Official web application domain',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'content_language_mode',
    category: 'general',
    key: 'content_language_mode',
    value: 'bengali_only',
    description: 'Global content language mode: bengali_only (default) or bilingual',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'exam_default_duration',
    category: 'exam_defaults',
    key: 'default_duration_minutes',
    value: 60,
    description: 'Standard default exam duration in minutes',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'exam_default_marks',
    category: 'exam_defaults',
    key: 'default_marks_per_q',
    value: 1.0,
    description: 'Standard default marks per correct question',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'exam_default_negative_marks',
    category: 'exam_defaults',
    key: 'default_negative_marks',
    value: 0.25,
    description: 'Standard default negative marking',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'exam_passing_percentage',
    category: 'exam_defaults',
    key: 'default_passing_percentage',
    value: 35,
    description: 'Standard passing score percentage',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub_currency',
    category: 'subscription',
    key: 'currency',
    value: 'INR',
    description: 'Platform transaction currency',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub_expiry_warning_days',
    category: 'subscription',
    key: 'expiry_warning_days',
    value: 7,
    description: 'Days before expiry to display renewal warning',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sys_maintenance_mode',
    category: 'system',
    key: 'maintenance_mode',
    value: false,
    description: 'Enable platform maintenance splash mode',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sys_app_version',
    category: 'system',
    key: 'app_version',
    value: '2.0.0',
    description: 'Platform production release version',
    updatedAt: new Date().toISOString(),
  },
];

export interface LocalPaymentGatewayRecord {
  gateway: string;
  key_id: string;
  key_secret?: string;
  webhook_secret?: string;
  is_active: boolean;
  updated_at?: string;
}

export const localPaymentGateways: Record<string, LocalPaymentGatewayRecord> = {
  razorpay: {
    gateway: 'razorpay',
    key_id: '',
    key_secret: '',
    webhook_secret: '',
    is_active: true,
    updated_at: new Date().toISOString(),
  },
};

export const localSupportTickets: SupportTicketItem[] = [
  {
    id: 'tkt_101',
    userId: 'user_student_1',
    studentName: 'Sourav Ganguly',
    studentEmail: 'sourav.aspirant@example.com',
    subject: 'Question 14 Answer Key in WBCS Prelims Mock #2',
    issue:
      'In question 14, option B was marked correct, but according to latest syllabus Option C is verified by standard texts.',
    category: 'Test Issue',
    priority: 'medium',
    status: 'open',
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    id: 'tkt_102',
    userId: 'user_student_2',
    studentName: 'Ananya Roy',
    studentEmail: 'ananya.wb@example.com',
    subject: 'UPI Payment debited but Pro Pass delayed',
    issue:
      'I paid ₹499 via Google Pay for 1-Year Pro Pass. UTR 428198271891. Please verify and activate.',
    category: 'Payment Issue',
    priority: 'high',
    status: 'resolved',
    resolutionNotes:
      'Verified with gateway logs. Transaction was captured. Pro Pass manually renewed for 365 days.',
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
];

export const localStaffUsers: AdminStaffMember[] = [
  {
    id: 'staff_super_admin',
    email: 'admin@practicekoro.online',
    fullName: 'Chief Super Admin',
    role: 'admin',
    adminRole: 'super_admin',
    createdAt: new Date(Date.now() - 3600000 * 24 * 30).toISOString(),
  },
  {
    id: 'staff_content_writer',
    email: 'writer@practicekoro.online',
    fullName: 'Debabrata Mukherjee (Content Specialist)',
    role: 'admin',
    adminRole: 'content_writer',
    createdAt: new Date(Date.now() - 3600000 * 24 * 14).toISOString(),
  },
  {
    id: 'staff_support_agent',
    email: 'support.lead@practicekoro.online',
    fullName: 'Priya Sen (Student Support Lead)',
    role: 'admin',
    adminRole: 'support_agent',
    createdAt: new Date(Date.now() - 3600000 * 24 * 7).toISOString(),
  },
];

export const localAuditLogs: AdminAuditLog[] = [
  {
    id: 'log_001',
    adminEmail: 'admin@practicekoro.online',
    adminName: 'Chief Super Admin',
    adminRole: 'super_admin',
    action: 'SETTINGS_UPDATE',
    entityType: 'settings',
    entityId: 'sys_maintenance_mode',
    entityName: 'Platform Maintenance Mode',
    details: { maintenance_mode: false },
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'log_002',
    adminEmail: 'writer@practicekoro.online',
    adminName: 'Debabrata Mukherjee',
    adminRole: 'content_writer',
    action: 'QUESTION_CREATE',
    entityType: 'question',
    entityId: 'q-wbp-const-001',
    entityName: 'WBP Constable Reasoning Pattern Q1',
    details: { exam: 'WBP Constable', subject: 'Reasoning', hasDiagram: true },
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'log_003',
    adminEmail: 'admin@practicekoro.online',
    adminName: 'Chief Super Admin',
    adminRole: 'super_admin',
    action: 'SUBSCRIPTION_MANUAL_GRANT',
    entityType: 'subscription',
    entityId: 'sub_manual_102',
    entityName: 'Ananya Roy (ananya.wb@example.com)',
    details: { plan: '1-Year Pro Pass', durationDays: 365, note: 'Resolved UPI discrepancy' },
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
];

// ─── Multi-Date Seeded Payments for Custom Date-Range Analytics ──────
const nowMs = Date.now();
const dayMs = 86400000;

export const localPayments: AdminPaymentRow[] = [
  {
    id: 'pay_today_1',
    userId: 'usr_001',
    studentName: 'Rohan Das',
    studentEmail: 'rohan.das@practicekoro.in',
    planId: 'pro_1_year',
    planTitle: '1-Year Pro All-Access',
    amount: 499,
    currency: 'INR',
    gateway: 'razorpay',
    orderId: 'ord_today_01',
    status: 'completed',
    createdAt: new Date(nowMs - 3600000 * 2).toISOString(), // Today
  },
  {
    id: 'pay_today_2',
    userId: 'usr_002',
    studentName: 'Moumita Banerjee',
    studentEmail: 'moumita.b@example.com',
    planId: 'pro_6_month',
    planTitle: '6-Month Pro Pass',
    amount: 299,
    currency: 'INR',
    gateway: 'razorpay',
    orderId: 'ord_today_02',
    status: 'completed',
    createdAt: new Date(nowMs - 3600000 * 5).toISOString(), // Today
  },
  {
    id: 'pay_yesterday_1',
    userId: 'usr_003',
    studentName: 'Rohan Mondal',
    studentEmail: 'rohan.wbp@example.com',
    planId: 'pro_1_year',
    planTitle: '1-Year Pro All-Access',
    amount: 499,
    currency: 'INR',
    gateway: 'razorpay',
    orderId: 'ord_yest_01',
    status: 'completed',
    createdAt: new Date(nowMs - dayMs - 3600000 * 3).toISOString(), // Yesterday
  },
  {
    id: 'pay_day3_1',
    userId: 'usr_004',
    studentName: 'Debolina Dutta',
    studentEmail: 'debolina@example.com',
    planId: 'pro_1_month',
    planTitle: '1-Month Pro Pass',
    amount: 99,
    currency: 'INR',
    gateway: 'razorpay',
    orderId: 'ord_d3_01',
    status: 'completed',
    createdAt: new Date(nowMs - dayMs * 3).toISOString(),
  },
  {
    id: 'pay_day5_1',
    userId: 'usr_005',
    studentName: 'Aritra Sen',
    studentEmail: 'aritra.sen@example.com',
    planId: 'pro_1_year',
    planTitle: '1-Year Pro All-Access',
    amount: 499,
    currency: 'INR',
    gateway: 'razorpay',
    orderId: 'ord_d5_01',
    status: 'completed',
    createdAt: new Date(nowMs - dayMs * 5).toISOString(),
  },
  {
    id: 'pay_day10_1',
    userId: 'usr_006',
    studentName: 'Suman Chatterjee',
    studentEmail: 'suman.wbcs@example.com',
    planId: 'pro_6_month',
    planTitle: '6-Month Pro Pass',
    amount: 299,
    currency: 'INR',
    gateway: 'razorpay',
    orderId: 'ord_d10_01',
    status: 'completed',
    createdAt: new Date(nowMs - dayMs * 10).toISOString(),
  },
  {
    id: 'pay_day18_1',
    userId: 'usr_007',
    studentName: 'Priyanka Naskar',
    studentEmail: 'priyanka.n@example.com',
    planId: 'pro_1_year',
    planTitle: '1-Year Pro All-Access',
    amount: 499,
    currency: 'INR',
    gateway: 'razorpay',
    orderId: 'ord_d18_01',
    status: 'completed',
    createdAt: new Date(nowMs - dayMs * 18).toISOString(),
  },
  {
    id: 'pay_day25_1',
    userId: 'usr_008',
    studentName: 'Bikram Sarkar',
    studentEmail: 'bikram.s@example.com',
    planId: 'pro_6_month',
    planTitle: '6-Month Pro Pass',
    amount: 299,
    currency: 'INR',
    gateway: 'razorpay',
    orderId: 'ord_d25_01',
    status: 'completed',
    createdAt: new Date(nowMs - dayMs * 25).toISOString(),
  },
  {
    id: 'pay_day45_1',
    userId: 'usr_009',
    studentName: 'Tanmoy Ghosh',
    studentEmail: 'tanmoy.g@example.com',
    planId: 'pro_1_year',
    planTitle: '1-Year Pro All-Access',
    amount: 499,
    currency: 'INR',
    gateway: 'razorpay',
    orderId: 'ord_d45_01',
    status: 'completed',
    createdAt: new Date(nowMs - dayMs * 45).toISOString(),
  },
  {
    id: 'pay_fixed_jan05',
    userId: 'usr_010',
    studentName: 'Joydeep Mukherjee',
    studentEmail: 'joydeep.m@example.com',
    planId: 'pro_1_year',
    planTitle: '1-Year Pro All-Access',
    amount: 499,
    currency: 'INR',
    gateway: 'razorpay',
    orderId: 'ord_jan05_01',
    status: 'completed',
    createdAt: '2026-01-05T10:30:00.000Z',
  },
  {
    id: 'pay_fixed_jan12',
    userId: 'usr_011',
    studentName: 'Sweta Karmakar',
    studentEmail: 'sweta.k@example.com',
    planId: 'pro_6_month',
    planTitle: '6-Month Pro Pass',
    amount: 299,
    currency: 'INR',
    gateway: 'razorpay',
    orderId: 'ord_jan12_01',
    status: 'completed',
    createdAt: '2026-01-12T14:45:00.000Z',
  },
  {
    id: 'pay_fixed_jan14',
    userId: 'usr_012',
    studentName: 'Dipankar Halder',
    studentEmail: 'dipankar.h@example.com',
    planId: 'pro_1_month',
    planTitle: '1-Month Pro Pass',
    amount: 99,
    currency: 'INR',
    gateway: 'razorpay',
    orderId: 'ord_jan14_01',
    status: 'completed',
    createdAt: '2026-01-14T18:20:00.000Z',
  },
];

// ─── Multi-Date Seeded Students for Signups Calculation ─────────────
export const localStudents: AdminStudentRow[] = [
  {
    id: 'usr_001',
    fullName: 'Rohan Das',
    email: 'rohan.das@practicekoro.in',
    phone: '+91 98301 11223',
    isPro: true,
    planId: 'pro_1_year',
    planTitle: '1-Year Pro All-Access',
    subscriptionStatus: 'active',
    subscriptionExpiresAt: new Date(nowMs + dayMs * 360).toISOString(),
    testsCompleted: 14,
    createdAt: new Date(nowMs - 3600000 * 4).toISOString(), // Today
  },
  {
    id: 'usr_002',
    fullName: 'Moumita Banerjee',
    email: 'moumita.b@example.com',
    phone: '+91 98312 22334',
    isPro: true,
    planId: 'pro_6_month',
    planTitle: '6-Month Pro Pass',
    subscriptionStatus: 'active',
    subscriptionExpiresAt: new Date(nowMs + dayMs * 175).toISOString(),
    testsCompleted: 9,
    createdAt: new Date(nowMs - 3600000 * 8).toISOString(), // Today
  },
  {
    id: 'usr_003',
    fullName: 'Rohan Mondal',
    email: 'rohan.wbp@example.com',
    phone: '+91 98323 33445',
    isPro: true,
    planId: 'pro_1_year',
    planTitle: '1-Year Pro All-Access',
    subscriptionStatus: 'active',
    subscriptionExpiresAt: new Date(nowMs + dayMs * 364).toISOString(),
    testsCompleted: 22,
    createdAt: new Date(nowMs - dayMs - 3600000 * 6).toISOString(), // Yesterday
  },
  {
    id: 'usr_004',
    fullName: 'Debolina Dutta',
    email: 'debolina@example.com',
    phone: '+91 98334 44556',
    isPro: false,
    testsCompleted: 4,
    createdAt: new Date(nowMs - dayMs * 3).toISOString(),
  },
  {
    id: 'usr_005',
    fullName: 'Aritra Sen',
    email: 'aritra.sen@example.com',
    phone: '+91 98345 55667',
    isPro: true,
    planId: 'pro_1_year',
    planTitle: '1-Year Pro All-Access',
    subscriptionStatus: 'active',
    subscriptionExpiresAt: new Date(nowMs + dayMs * 360).toISOString(),
    testsCompleted: 18,
    createdAt: new Date(nowMs - dayMs * 5).toISOString(),
  },
  {
    id: 'usr_006',
    fullName: 'Suman Chatterjee',
    email: 'suman.wbcs@example.com',
    phone: '+91 98356 66778',
    isPro: true,
    planId: 'pro_6_month',
    planTitle: '6-Month Pro Pass',
    subscriptionStatus: 'active',
    subscriptionExpiresAt: new Date(nowMs + dayMs * 170).toISOString(),
    testsCompleted: 31,
    createdAt: new Date(nowMs - dayMs * 10).toISOString(),
  },
  {
    id: 'usr_007',
    fullName: 'Priyanka Naskar',
    email: 'priyanka.n@example.com',
    phone: '+91 98367 77889',
    isPro: true,
    planId: 'pro_1_year',
    planTitle: '1-Year Pro All-Access',
    subscriptionStatus: 'active',
    subscriptionExpiresAt: new Date(nowMs + dayMs * 347).toISOString(),
    testsCompleted: 25,
    createdAt: new Date(nowMs - dayMs * 18).toISOString(),
  },
  {
    id: 'usr_008',
    fullName: 'Bikram Sarkar',
    email: 'bikram.s@example.com',
    phone: '+91 98378 88990',
    isPro: false,
    testsCompleted: 7,
    createdAt: new Date(nowMs - dayMs * 25).toISOString(),
  },
  {
    id: 'usr_009',
    fullName: 'Tanmoy Ghosh',
    email: 'tanmoy.g@example.com',
    phone: '+91 98389 99001',
    isPro: true,
    planId: 'pro_1_year',
    planTitle: '1-Year Pro All-Access',
    subscriptionStatus: 'active',
    subscriptionExpiresAt: new Date(nowMs + dayMs * 320).toISOString(),
    testsCompleted: 19,
    createdAt: new Date(nowMs - dayMs * 45).toISOString(),
  },
  {
    id: 'usr_jan02',
    fullName: 'Sandip Roy',
    email: 'sandip.r@example.com',
    phone: '+91 98300 00112',
    isPro: true,
    planId: 'pro_1_year',
    planTitle: '1-Year Pro All-Access',
    subscriptionStatus: 'active',
    testsCompleted: 12,
    createdAt: '2026-01-02T09:15:00.000Z',
  },
  {
    id: 'usr_jan05',
    fullName: 'Joydeep Mukherjee',
    email: 'joydeep.m@example.com',
    phone: '+91 98300 00113',
    isPro: true,
    planId: 'pro_1_year',
    planTitle: '1-Year Pro All-Access',
    subscriptionStatus: 'active',
    testsCompleted: 15,
    createdAt: '2026-01-05T08:30:00.000Z',
  },
  {
    id: 'usr_jan12',
    fullName: 'Sweta Karmakar',
    email: 'sweta.k@example.com',
    phone: '+91 98300 00114',
    isPro: true,
    planId: 'pro_6_month',
    planTitle: '6-Month Pro Pass',
    subscriptionStatus: 'active',
    testsCompleted: 8,
    createdAt: '2026-01-12T11:45:00.000Z',
  },
  {
    id: 'usr_jan14',
    fullName: 'Dipankar Halder',
    email: 'dipankar.h@example.com',
    phone: '+91 98300 00115',
    isPro: true,
    planId: 'pro_1_month',
    planTitle: '1-Month Pro Pass',
    subscriptionStatus: 'active',
    testsCompleted: 6,
    createdAt: '2026-01-14T15:20:00.000Z',
  },
];

// ─── Item Analysis Seed Store (Question Accuracy & Difficulty) ──────
export const localItemAnalysisStore: QuestionItemAnalysis[] = [
  {
    questionId: 'q-lit-04',
    questionText:
      'কোন কাব্যগ্রন্থটির জন্য মাইকেল মধুসূদন দত্ত অমিত্রাক্ষর ছন্দের প্রথম সার্থক প্রয়োগ ঘটান?',
    questionBengali:
      'কোন কাব্যগ্রন্থটির জন্য মাইকেল মধুসূদন দত্ত অমিত্রাক্ষর ছন্দের প্রথম সার্থক প্রয়োগ ঘটান?',
    subjectId: 'sub_bengali',
    subjectName: 'বাংলা সাহিত্য ও ব্যাকরণ',
    chapterId: 'chap_bengali_modern',
    chapterName: 'আধুনিক বাংলা কাব্য ও নাটক',
    examId: 'exam_wbcs',
    examTitle: 'WBCS Executive Examination',
    testId: 'test_wbcs_bengali_01',
    testTitle: 'WBCS Bengali Literature Mastery Mock',
    declaredDifficulty: 'medium',
    empiricalDifficulty: 'extreme',
    totalAttempts: 154,
    correctCount: 24,
    wrongCount: 126,
    skippedCount: 4,
    accuracyRate: 15.6,
    failureRate: 81.8, // >= 80% failure rate!
    avgTimeSpentSeconds: 78,
    isHighFailure: true,
    isTimeTrap: false,
    isMisclassified: true, // declared medium but actual extreme failure
    options: {
      A: 'তিলোত্তমাসম্ভব কাব্য',
      B: 'মেঘনাদবধ কাব্য',
      C: 'পদ্মাবতী নাটক',
      D: 'বীরাঙ্গনা কাব্য',
    },
    correctOption: 'A',
    optionDistribution: {
      A: 15.6, // Correct option (only 15.6%)
      B: 58.4, // Trap distractor! Most students mistakenly chose মেঘনাদবধ
      C: 18.2,
      D: 5.2,
    },
    explanation:
      'মাইকেল মধুসূদন দত্ত ১৮৬০ সালে প্রকাশিত "তিলোত্তমাসম্ভব কাব্য"-এ প্রথম সার্থকভাবে অমিত্রাক্ষর ছন্দ (Blank Verse) প্রয়োগ করেন। তবে এই ছন্দের চূড়ান্ত মহাকাব্যিক পরাকাষ্ঠা ঘটে ১৮৬১ সালে "মেঘনাদবধ কাব্য"-এ। ৫৮% শিক্ষার্থী ভুলবশত মেঘনাদবধ নির্বাচন করেছে।',
  },
  {
    questionId: 'q-math-02',
    questionText:
      'একটি নির্বাচনে দুইজন প্রার্থীর মধ্যে বিজয়ী প্রার্থী মোট প্রদত্ত ভোটের ৫৮% পেয়ে ৪,৮০০ ভোটে জয়লাভ করলেন। যদি ২০% ভোট অবৈধ ঘোষিত হয়ে থাকে, তবে ভোটার তালিকায় মোট ভোটারের সংখ্যা কত ছিল?',
    questionBengali:
      'একটি নির্বাচনে দুইজন প্রার্থীর মধ্যে বিজয়ী প্রার্থী মোট প্রদত্ত ভোটের ৫৮% পেয়ে ৪,৮০০ ভোটে জয়লাভ করলেন। যদি ২০% ভোট অবৈধ ঘোষিত হয়ে থাকে, তবে ভোটার তালিকায় মোট ভোটারের সংখ্যা কত ছিল?',
    subjectId: 'sub_math',
    subjectName: 'পাটিগণিত ও সংখ্যাতত্ত্ব',
    chapterId: 'chap_math_percentage',
    chapterName: 'শতকরা ও অনুপাত',
    examId: 'exam_wb_police',
    examTitle: 'West Bengal Police Constable & SI',
    testId: 'test_wbp_math_01',
    testTitle: 'WBP Arithmetic Full Speed Mock',
    declaredDifficulty: 'medium',
    empiricalDifficulty: 'extreme',
    totalAttempts: 168,
    correctCount: 26,
    wrongCount: 138,
    skippedCount: 4,
    accuracyRate: 15.5,
    failureRate: 82.1, // >= 80% failure rate!
    avgTimeSpentSeconds: 124, // > 90s Time Trap!
    isHighFailure: true,
    isTimeTrap: true, // Both High Failure and Time Trap!
    isMisclassified: true,
    options: {
      A: '৩৭,৫০০',
      B: '৩০,০০০',
      C: '৪০,০০০',
      D: '৪২,০০০',
    },
    correctOption: 'A',
    optionDistribution: {
      A: 15.5,
      B: 64.3, // Calculation error without invalid vote adjustment
      C: 12.5,
      D: 5.4,
    },
    explanation:
      'ধরি মোট ভোটার = x। বৈধ ভোট = ০.৮x। বিজয়ী ও পরাজিত প্রার্থীর ব্যবধান = (৫৮% - ৪২%) = ১৬% বৈধ ভোট। সুতরাং ০.১৬ × ০.৮x = ৪,৮০০ => ০.১২৮x = ৪,৮০০ => x = ৩৭,৫০০। ৬৪% ছাত্র ২০% অবৈধ ভোটের হিসাব বাদ দেওয়ায় ৩০,০০০ উত্তর বেছে নিয়েছে।',
  },
  {
    questionId: 'q-hist-03',
    questionText:
      '১৮৫৭ সালের মহাবিদ্রোহ চলাকালে অযোধ্যায় (লখনউ) ব্রিটিশ সৈন্যবাহিনীর বিরুদ্ধে সিপাহীদের কার্যকর নেতৃত্ব কে প্রদান করেছিলেন?',
    questionBengali:
      '১৮৫৭ সালের মহাবিদ্রোহ চলাকালে অযোধ্যায় (লখনউ) ব্রিটিশ সৈন্যবাহিনীর বিরুদ্ধে সিপাহীদের কার্যকর নেতৃত্ব কে প্রদান করেছিলেন?',
    subjectId: 'sub_history',
    subjectName: 'ভারতের আধুনিক ইতিহাস ও জাতীয় আন্দোলন',
    chapterId: 'chap_hist_1857',
    chapterName: 'মহাবিদ্রোহ ও ব্রিটিশ নীতি',
    examId: 'exam_wbcs',
    examTitle: 'WBCS Executive Examination',
    testId: 'test_wbcs_hist_02',
    testTitle: 'Indian Freedom Movement Core Test',
    declaredDifficulty: 'easy',
    empiricalDifficulty: 'extreme',
    totalAttempts: 145,
    correctCount: 28,
    wrongCount: 116,
    skippedCount: 1,
    accuracyRate: 19.3,
    failureRate: 80.0, // >= 80% failure rate!
    avgTimeSpentSeconds: 48,
    isHighFailure: true,
    isTimeTrap: false,
    isMisclassified: true, // author wrote easy, but 80% candidates failed!
    options: {
      A: 'নানা সাহেব',
      B: 'বেগম হজরত মহল',
      C: 'খান বাহাদুর খান',
      D: 'মৌলভি আহমদুল্লাহ',
    },
    correctOption: 'B',
    optionDistribution: {
      A: 42.1, // Distractor trap (Nana Saheb led Kanpur, not Lucknow)
      B: 19.3, // Correct (Begum Hazrat Mahal)
      C: 8.3,
      D: 29.7, // Maulvi Ahmadullah also operated near Faizabad/Awadh
    },
    explanation:
      'লখনউতে মহাবিদ্রোহের মূল নেতৃত্ব দেন বেগম হজরত মহল। তিনি তার নাবালক পুত্র বিজ্রিস কাদিরকে নবাব ঘোষণা করে যুদ্ধ পরিচালনা করেন। কানপুরে নেতৃত্ব দেন নানা সাহেব।',
  },
  {
    questionId: 'q-reas-03',
    questionText:
      'আটজন ব্যক্তি A, B, C, D, E, F, G, H একটি বৃত্তাকার টেবিলের চারিদিকে কেন্দ্রের দিকে মুখ করে বসে আছেন। B বসেছে D-এর ডানদিকে তৃতীয় স্থানে এবং F-এর বামদিকে দ্বিতীয় স্থানে। H-এর অবস্থান নির্ণয় করো।',
    questionBengali:
      'আটজন ব্যক্তি A, B, C, D, E, F, G, H একটি বৃত্তাকার টেবিলের চারিদিকে কেন্দ্রের দিকে মুখ করে বসে আছেন। B বসেছে D-এর ডানদিকে তৃতীয় স্থানে এবং F-এর বামদিকে দ্বিতীয় স্থানে। H-এর অবস্থান নির্ণয় করো।',
    subjectId: 'sub_reasoning',
    subjectName: 'যৌক্তিক বিশ্লেষণ ও রিজনিং',
    chapterId: 'chap_reas_seating',
    chapterName: 'বৃত্তাকার ও রৈখিক আসন বিন্যাস',
    examId: 'exam_wb_police',
    examTitle: 'West Bengal Police Constable & SI',
    testId: 'test_wbp_reas_02',
    testTitle: 'Advanced Seating & Puzzles Mock',
    declaredDifficulty: 'hard',
    empiricalDifficulty: 'moderate',
    totalAttempts: 122,
    correctCount: 62,
    wrongCount: 46,
    skippedCount: 14,
    accuracyRate: 50.8,
    failureRate: 37.7,
    avgTimeSpentSeconds: 148, // > 90s Time Trap!
    isHighFailure: false,
    isTimeTrap: true, // Time Trap!
    isMisclassified: false,
    options: {
      A: 'C এবং E এর ঠিক মাঝে',
      B: 'F এর মুখোমুখি বিপরীত দিকে',
      C: 'A এর ডানদিকে দ্বিতীয় স্থানে',
      D: 'D এর বামদিকে দ্বিতীয় স্থানে',
    },
    correctOption: 'B',
    optionDistribution: {
      A: 18.0,
      B: 50.8,
      C: 17.2,
      D: 10.7,
    },
    explanation:
      'আসন বিন্যাস তৈরি করলে দেখা যায় F এবং H পরস্পরের মুখোমুখি বিপরীত বিন্দুতে অবস্থান করছে। প্রশ্নটি সমাধান করতে প্রার্থীদের গড়ে ১৪৮ সেকেন্ড লেগেছে, যা আদর্শ সময়ের (৬০ সে.) দ্বিগুণের বেশি।',
  },
  {
    questionId: 'q-sci-05',
    questionText:
      'বায়ুমণ্ডলে ওজন স্তরের ঘনত্ব পরিমাপের জন্য নিচের কোন বৈজ্ঞানিক এককটি ব্যবহার করা হয়?',
    questionBengali:
      'বায়ুমণ্ডলে ওজন স্তরের ঘনত্ব পরিমাপের জন্য নিচের কোন বৈজ্ঞানিক এককটি ব্যবহার করা হয়?',
    subjectId: 'sub_science',
    subjectName: 'সাধারণ বিজ্ঞান ও পরিবেশ বিদ্যা',
    chapterId: 'chap_sci_atmosphere',
    chapterName: 'বায়ুমণ্ডল ও পরিবেশ দূষণ',
    examId: 'exam_wbcs',
    examTitle: 'WBCS Executive Examination',
    testId: 'test_wbcs_sci_01',
    testTitle: 'WBCS General Science Prelims Drill',
    declaredDifficulty: 'easy',
    empiricalDifficulty: 'easy',
    totalAttempts: 195,
    correctCount: 158,
    wrongCount: 32,
    skippedCount: 5,
    accuracyRate: 81.0,
    failureRate: 16.4,
    avgTimeSpentSeconds: 28,
    isHighFailure: false,
    isTimeTrap: false,
    isMisclassified: false,
    options: {
      A: 'ডবসন একক (Dobson Unit)',
      B: 'পাস্কাল (Pascal)',
      C: 'ক্যান্ডেলা (Candela)',
      D: 'অ্যাম্পিয়ার (Ampere)',
    },
    correctOption: 'A',
    optionDistribution: {
      A: 81.0,
      B: 12.3,
      C: 4.1,
      D: 1.5,
    },
    explanation:
      'ওজন স্তরের মোট ঘনত্ব পরিমাপ করতে ডবসন ইউনিট (DU) ব্যবহৃত হয়। ১ ডবসন ইউনিট হলো মানক চাপ ও তাপমাত্রায় ০.০১ মিমি পুরু বিশুদ্ধ ওজন স্তর।',
  },
  {
    questionId: 'q-geo-02',
    questionText:
      'পশ্চিমবঙ্গের সুন্দরবন অঞ্চলের প্রধান ম্যানগ্রোভ বনভূমির জীববৈচিত্র্য সংরক্ষণের ক্ষেত্রে ইউনেস্কো কোন সালে এটিকে ওয়ার্ল্ড হেরিটেজ সাইট হিসেবে ঘোষণা করে?',
    questionBengali:
      'পশ্চিমবঙ্গের সুন্দরবন অঞ্চলের প্রধান ম্যানগ্রোভ বনভূমির জীববৈচিত্র্য সংরক্ষণের ক্ষেত্রে ইউনেস্কো কোন সালে এটিকে ওয়ার্ল্ড হেরিটেজ সাইট হিসেবে ঘোষণা করে?',
    subjectId: 'sub_geography',
    subjectName: 'পশ্চিমবঙ্গ ও ভারতের ভূগোল',
    chapterId: 'chap_geo_wb',
    chapterName: 'পশ্চিমবঙ্গের ভূপ্রকৃতি ও অরণ্য',
    examId: 'exam_wbcs',
    examTitle: 'WBCS Executive Examination',
    testId: 'test_wbcs_geo_01',
    testTitle: 'West Bengal Geography Core Mock',
    declaredDifficulty: 'easy',
    empiricalDifficulty: 'extreme',
    totalAttempts: 172,
    correctCount: 31,
    wrongCount: 139,
    skippedCount: 2,
    accuracyRate: 18.0,
    failureRate: 80.8, // >= 80% failure rate!
    avgTimeSpentSeconds: 38,
    isHighFailure: true,
    isTimeTrap: false,
    isMisclassified: true, // Declared easy, but 80.8% failure!
    options: {
      A: '১৯৮৪',
      B: '১৯৮৭',
      C: '১৯৮৯',
      D: '২০০১',
    },
    correctOption: 'B',
    optionDistribution: {
      A: 34.9, // National park declaration year (1984) trap!
      B: 18.0, // Correct UNESCO World Heritage (1987)
      C: 38.4, // Biosphere reserve (1989) trap!
      D: 6.4,
    },
    explanation:
      'সুন্দরবন জাতীয় উদ্যানকে ১৯৮৭ সালে ইউনেস্কো ওয়ার্ল্ড হেরিটেজ সাইট হিসেবে স্বীকৃতি দেয়। ১৯৮৪ সালে এটি জাতীয় উদ্যান এবং ১৯৮৯ সালে বায়োস্ফিয়ার রিজার্ভ হিসেবে ঘোষিত হয়েছিল। ৩৫% শিক্ষার্থী ১৯৮৪ এবং ৩৮% শিক্ষার্থী ১৯৮৯ নির্বাচন করেছে।',
  },
];
