import React, { useEffect, useState } from 'react';
import { CalendarClock, Plus, RefreshCw } from 'lucide-react';
import { api, type LiveTest } from '@/services/api';
import type { MockTest, TestSeries } from '@/types';

export const AdminLiveTests: React.FC = () => {
  const [items,setItems]=useState<LiveTest[]>([]); const [tests,setTests]=useState<MockTest[]>([]); const [series,setSeries]=useState<TestSeries[]>([]);
  const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false);
  const [form,setForm]=useState({title:'',testId:'',testSeriesId:'',scheduledStartAt:'',scheduledEndAt:'',instructions:'',rankingEnabled:true,subscriptionRequired:false});
  const load=async()=>{ const [l,t,s]=await Promise.all([api.getLiveTestsForAdmin(),api.getAllAdminTests(),api.getTestSeries()]); setItems(l); setTests(t); setSeries(s); };
  useEffect(()=>{load().catch(console.error)},[]);
  const create=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{const t=tests.find(x=>x.id===form.testId);await api.createLiveTest({title:form.title,test_id:form.testId,test_series_id:form.testSeriesId||null,exam_id:t?.examId||null,scheduled_start_at:new Date(form.scheduledStartAt).toISOString(),scheduled_end_at:new Date(form.scheduledEndAt).toISOString(),duration_minutes:t?.durationMinutes||60,instructions:form.instructions,ranking_enabled:form.rankingEnabled,subscription_required:form.subscriptionRequired,status:'scheduled',visibility:'public',result_visibility:'immediate'});setOpen(false);setForm({title:'',testId:'',testSeriesId:'',scheduledStartAt:'',scheduledEndAt:'',instructions:'',rankingEnabled:true,subscriptionRequired:false});await load()}finally{setSaving(false)}};
  const setStatus=async(id:string,status:string)=>{await api.updateLiveTest(id,{status});await load()};
  return <div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-black">Live Tests</h1><p className="text-sm text-slate-500">Schedule and control real-time examination events.</p></div><div className="flex gap-2"><button onClick={()=>load()} className="rounded-xl border px-3 py-2"><RefreshCw className="h-4 w-4"/></button><button onClick={()=>setOpen(true)} className="rounded-xl bg-[#0158FC] px-4 py-2 text-sm font-bold text-white"><Plus className="mr-2 inline h-4 w-4"/>Create Live Test</button></div></div>
  <div className="grid gap-4">{items.map(item=><div key={item.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><CalendarClock className="h-5 w-5 text-[#0158FC]"/><h2 className="font-black">{item.title}</h2><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold uppercase">{item.status}</span></div><p className="mt-1 text-xs text-slate-500">{new Date(item.scheduledStartAt).toLocaleString()} · {item.durationMinutes} min · {item.test?.totalQuestions||0} questions</p></div><div className="flex gap-2">{item.status==='scheduled'&&<button onClick={()=>setStatus(item.id,'live')} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Start</button>}{item.status==='live'&&<button onClick={()=>setStatus(item.id,'completed')} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">End</button>}{item.status!=='cancelled'&&item.status!=='completed'&&<button onClick={()=>setStatus(item.id,'cancelled')} className="rounded-lg bg-rose-50 px-3 py-2 text-xs font-bold text-rose-600">Cancel</button>}</div></div></div>)}</div>
  {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={create} className="w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Create Live Test</h2><button type="button" onClick={()=>setOpen(false)}>×</button></div><div className="mt-5 grid gap-3"><input required placeholder="Live test title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="rounded-xl border p-3 text-sm"/><select required value={form.testId} onChange={e=>setForm({...form,testId:e.target.value})} className="rounded-xl border p-3 text-sm"><option value="">Select Test</option>{tests.filter(t=>t.isActive).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><select value={form.testSeriesId} onChange={e=>setForm({...form,testSeriesId:e.target.value})} className="rounded-xl border p-3 text-sm"><option value="">No Test Series</option>{series.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select><div className="grid grid-cols-2 gap-3"><input required type="datetime-local" value={form.scheduledStartAt} onChange={e=>setForm({...form,scheduledStartAt:e.target.value})} className="rounded-xl border p-3 text-sm"/><input required type="datetime-local" value={form.scheduledEndAt} onChange={e=>setForm({...form,scheduledEndAt:e.target.value})} className="rounded-xl border p-3 text-sm"/></div><textarea placeholder="Instructions" value={form.instructions} onChange={e=>setForm({...form,instructions:e.target.value})} className="min-h-24 rounded-xl border p-3 text-sm"/><label className="text-sm"><input type="checkbox" checked={form.rankingEnabled} onChange={e=>setForm({...form,rankingEnabled:e.target.checked})}/> Enable ranking</label><label className="text-sm"><input type="checkbox" checked={form.subscriptionRequired} onChange={e=>setForm({...form,subscriptionRequired:e.target.checked})}/> Pro Pass required</label><button disabled={saving} className="rounded-xl bg-[#0158FC] p-3 font-bold text-white">{saving?'Creating...':'Create Live Test'}</button></div></form></div>}</div>;
};
